services:
  mysql_service:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: citas_medicas
      MYSQL_USER: dbuser_poli
      MYSQL_PASSWORD: dbpassword_poli
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - app-network
  php_service:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/app
      - /app/vendor
    ports:
      - "9000:9000"
    networks:
      - app-network
    depends_on:
      - mysql_service
  jenkins:
    build:
      context: .
      dockerfile: docker/jenkins/Dockerfile
    container_name: jenkins
    user: root
    ports:
      - "8081:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # importante para usar Docker desde Jenkins
      - ./:/app  # monta tu código en Jenkins
networks:
  app-network:
    driver: bridge
volumes:
  jenkins_home:

